fix return type at evaluate function
Spyros-Av/Poker_Hand_Evaluation pull request #3
Opened 2021-07-28 08:10 UTC by Spyros-Av

2021-07-28 17:42 UTC, stacon commented
@Spyros-Av I don't see the requested fixes from the code review on the pull request. Do you need some help with that?

2021-07-28 18:52 UTC, Spyros-Av commented
> @Spyros-Av I don't see the requested fixes from the code review on the pull request. Do you need some help with that?

Iadded an object constructor from line 95 to 98, also the 'evaluate' function return objects.  Aren't these changes visible?

2021-07-28 20:58 UTC, stacon commented
I still see the old codebase @Spyros-Av 
![image](https://user-images.githubusercontent.com/19994733/127394892-6ff034c7-93d6-44f5-8ce9-31dd42ea130f.png)

We can catchup tomorrow to give you a small tour on GitHub usage. What do you think?

2021-07-28 21:16 UTC, Spyros-Av commented
> I still see the old codebase @Spyros-Av
> ![image](https://user-images.githubusercontent.com/19994733/127394892-6ff034c7-93d6-44f5-8ce9-31dd42ea130f.png)
> 
> We can catchup tomorrow to give you a small tour on GitHub usage. What do you think?

Sure. Lets catch up tomorrow, I believe it's a good idea.

2021-07-29 13:45 UTC, stacon requested changes
Check comments

2021-07-29 13:45 UTC, stacon commented on poker.js
> +    const player = new PlayerHand(handType.ROYAL_FLUSH, strength);
Keep your naming consistent even if it is verbose `playerHand` is more descriptive. What do you think

2021-07-29 13:45 UTC, stacon commented on poker.js
> +
Lets go with a more functional approach I'd say..
`new` keyword isn't needed anymore
```suggestion
const PlayerHand = (hand, highCard) => ({
  hand,
  highCard,
});

```

2021-07-29 13:45 UTC, stacon commented on poker.js
>    (rank[i] === 'J' || rank[i] === 'j') ? rank[i] = 11 :
You can always lowercase the rank[i] before doing the comparison just for shorter and cleaner code.

2021-07-30 07:51 UTC, Spyros-Av commented on poker.js
> +
Done!

2021-07-30 11:43 UTC, stacon approved these changes
Good job

2021-07-30 11:43 UTC, merged